#  ██████╗ ██╗ ██████╗███████╗     ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
#  ██╔══██╗██║██╔════╝██╔════╝    ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
#  ██████╔╝██║██║     █████╗      ██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
#  ██╔══██╗██║██║     ██╔══╝      ██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
#  ██║  ██║██║╚██████╗███████╗    ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
#  ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝     ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
#  Author : z0mbi3
#  url    : https://github.com/gh0stzk/dotfiles
#  Info   : Alacritty Colorschemes for the 12 rices.

schemes:
# Colors (Pencil light) Aline Rice
  aline_pencil_light: &aline_pencil_light
    primary:
      background: '#e5eafe'
      foreground: '#51576d'
    normal:
      black:   '#212121'
      red:     '#c30771'
      green:   '#10a778'
      yellow:  '#a89c14'
      blue:    '#008ec4'
      magenta: '#523c79'
      cyan:    '#20a5ba'
      white:   '#51576d'
    bright:
      black:   '#212121'
      red:     '#fb007a'
      green:   '#5fd7af'
      yellow:  '#f3e430'
      blue:    '#20bbfc'
      magenta: '#6855de'
      cyan:    '#4fb8cc'
      white:   '#51576d'
    cursor:
      cursor: '#20bbfc'
      text:	'#e5eafe'
# Colors Andrea Rice
  andrea_color_scheme: &andrea_color_scheme
    primary:
      background: '#F5EEE6'
      foreground: '#6d6a78'
    normal:
      black:   '#80859d'
      red:     '#c04364'
      green:   '#abd77a'
      yellow:  '#ffcc57'
      blue:    '#67d4f1'
      magenta: '#7a7498'
      cyan:    '#9bf4d5'
      white:   '#b0b0b0'
    bright:
      black:   '#80859d'
      red:     '#c03f61'
      green:   '#a1d16c'
      yellow:  '#f2be47'
      blue:    '#50bfdc'
      magenta: '#605692'
      cyan:    '#83edc8'
      white:   '#b0b0b0'
    cursor:
      cursor: '#7a7498'
      text:	'#F5EEE6'
# Colors (Rose-Pine Moon) Cristina Rice
  cristina_rose_pine: &cristina_rose_pine
    primary:
      background: '#1f1d29'
      foreground: '#eaeaea'
    normal:
      black:   '#6f6e85'
      red:     '#ea6f91'
      green:   '#9bced7'
      yellow:  '#f1ca93'
      blue:    '#34738e'
      magenta: '#c3a5e6'
      cyan:    '#eabbb9'
      white:   '#faebd7'
    bright:
      black:   '#6f6e85'
      red:     '#ea6f91'
      green:   '#9bced7'
      yellow:  '#f1ca93'
      blue:    '#34738e'
      magenta: '#c3a5e6'
      cyan:    '#ebbcba'
      white:   '#e0def4'
    cursor:
      cursor: '#c3a5e6'
      text:	'#1f1d29'
# Colors Cynthia Rice
  cynthia_color_scheme: &cynthia_color_scheme
    primary:
      background: '#1f2329'
      foreground: '#b8bfe5'
    normal:
      black:   '#0f1319'
      red:     '#644d66'
      green:   '#375759'
      yellow:  '#736871'
      blue:    '#3f5273'
      magenta: '#543f66'
      cyan:    '#324f66'
      white:   '#b3b3b3'
    bright:
      black:   '#b3b3b3'
      red:     '#735771'
      green:   '#3f6566'
      yellow:  '#807476'
      blue:    '#465b80'
      magenta: '#533969'
      cyan:    '#385a73'
      white:   '#e5e5e5'
    cursor:
      cursor: '#465b80'
      text:	'#e5e5e5'
# Colors (Tokyo Night) Emilia Rice
  emilia_tokyo_night: &emilia_tokyo_night
    primary:
      background: '#1a1b26'
      foreground: '#c0caf5'
    normal:
      black:   '#414868'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#bb9af7'
      cyan:    '#7dcfff'
      white:   '#787c99'
    bright:
      black:   '#414868'
      red:     '#f7768e'
      green:   '#9ece6a'
      yellow:  '#e0af68'
      blue:    '#7aa2f7'
      magenta: '#bb9af7'
      cyan:    '#7dcfff'
      white:   '#c0caf5'
    cursor:
      cursor: '#bb9af7'
      text:	'#1a1b26'
# Colors (Onedark) Isabel Rice
  isabel_onedark: &isabel_onedark
    primary:
      background: '#14171c'
      foreground: '#b8bfe5'
    normal:
      black:   '#5c6370'
      red:     '#be5046'
      green:   '#81ae5f'
      yellow:  '#d19a66'
      blue:    '#4889be'
      magenta: '#7560d3'
      cyan:    '#49919a'
      white:   '#c5cddb'
    bright:
      black:   '#5c6370'
      red:     '#e06c75'
      green:   '#98c379'
      yellow:  '#e5c07b'
      blue:    '#61afef'
      magenta: '#8677cf'
      cyan:    '#56b6c2'
      white:   '#abb2bf'
    cursor:
      cursor: '#abb2bf'
      text:	'#14171c'
# Colors (CyberPunk) Jan Rice
  jan_cyberpunk: &jan_cyberpunk
    primary:
      background: '#070219'
      foreground: '#c0caf5'
    normal:
      black:   '#626483'
      red:     '#fb007a'
      green:   '#a6e22e'
      yellow:  '#f3e430'
      blue:    '#58AFC2'
      magenta: '#583794'
      cyan:    '#926BCA'
      white:   '#d9d9d9'
    bright:
      black:   '#626483'
      red:     '#fb007a'
      green:   '#a6e22e'
      yellow:  '#f3e430'
      blue:    '#58AFC2'
      magenta: '#472575'
      cyan:    '#926BCA'
      white:   '#f1f1f1'
    cursor:
      cursor: '#fb007a'
      text:	'#070219'
# Colors (Zombie-Night color scheme) Karla Rice
  karla_z0mbi3_night: &karla_z0mbi3_night
    primary:
      background: '#0E1113'
      foreground: '#afb1db'
    normal:
      black:   '#2d2b36'
      red:     '#e7034a'
      green:   '#61b33e'
      yellow:  '#ffb964'
      blue:    '#5884d4'
      magenta: '#7a44e3'
      cyan:    '#7df0f0'
      white:   '#faf7ff'
    bright:
      black:   '#373542'
      red:     '#e71c5b'
      green:   '#6fb352'
      yellow:  '#ffb964'
      blue:    '#5f90ea'
      magenta: '#8656e3'
      cyan:    '#97f0f0'
      white:   '#fdfcff'
    cursor:
      cursor: '#8656e3'
      text:	'#0b0b12'
# Colors (Nord) Melissa Rice
  melissa_nord: &melissa_nord
    primary:
      background: '#2e3440'
      foreground: '#d8dee9'
    normal:
      black:   '#4c566a'
      red:     '#bf616a'
      green:   '#a3be8c'
      yellow:  '#ebcb8b'
      blue:    '#81a1c1'
      magenta: '#b48ead'
      cyan:    '#88c0d0'
      white:   '#e5e9f0'
    bright:
      black:   '#4c566a'
      red:     '#bf616a'
      green:   '#a3be8c'
      yellow:  '#ebcb8b'
      blue:    '#81a1c1'
      magenta: '#b48ead'
      cyan:    '#8fbcbb'
      white:   '#eceff4'
    cursor:
      cursor: '#81a1c1'
      text:	'#2e3440'
# Colors (Elenapan) Pamela Rice
  pamela_color_scheme: &pamela_color_scheme
    primary:
      background: '#1D1F28'
      foreground: '#FDFDFD'
    normal:
      black:   '#3D4C5F'
      red:     '#F37F97'
      green:   '#5ADECD'
      yellow:  '#F2A272'
      blue:    '#8897F4'
      magenta: '#C574DD'
      cyan:    '#79E6F3'
      white:   '#FDFDFD'
    bright:
      black:   '#56687E'
      red:     '#FF4971'
      green:   '#18E3C8'
      yellow:  '#FF8037'
      blue:    '#556FFF'
      magenta: '#B043D1'
      cyan:    '#3FDCEE'
      white:   '#BEBEC1'
    cursor:
      cursor: '#FF4971'
      text:	'#1D1F28'
# Colors (Gruvbox) Silvia Rice
  silvia_gruvbox: &silvia_gruvbox
    primary:
      background: '#282828'
      foreground: '#fbf1c7'
    normal:
      black:   '#a89984'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#ebdbb2'
    bright:
      black:   '#a89984'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
    cursor:
      cursor: '#fbf1c7'
      text:	'#282828'
# Colors (Decay, decayce variant) z0mbi3 Rice
  z0mbi3_decay: &z0mbi3_decay
    primary:
      background: '#0d0f18'
      foreground: '#a5b6cf'
    normal:
      black:   '#3d414f'
      red:     '#dd6777'
      green:   '#90ceaa'
      yellow:  '#ecd3a0'
      blue:    '#86aaec'
      magenta: '#c296eb'
      cyan:    '#93cee9'
      white:   '#cbced3'
    bright:
      black:   '#3d414f'
      red:     '#dd6777'
      green:   '#90ceaa'
      yellow:  '#ecd3a0'
      blue:    '#86aaec'
      magenta: '#c296eb'
      cyan:    '#93cee9'
      white:   '#cbced3'
    cursor:
      cursor: '#a5b6cf'
      text:	'#0d0f18'

# Set the color scheme for the actual rice.
colors: *emilia_tokyo_night
