# Colors for Andrea Rice

# Default colors
[colors.primary]
background = "#f5eee6"
foreground = "#2b2530"

# Cursor colors
[colors.cursor]
cursor = "#2b2530"
text = "#f5eee6"

# Normal colors
[colors.normal]
black = "#5c595e"
red = "#DA103F"
green = "#1EB980"
yellow = "#ffc338"
blue = "#67d4f1"
magenta = "#6b28de"
cyan = "#2eccca"
white = "#e1e2e7"

# Bright colors
[colors.bright]
black = "#5c595e"
red = "#F43E5C"
green = "#07DA8C"
yellow = "#ffcc57"
blue = "#3FC6DE"
magenta = "#7a3fde"
cyan = "#1EAEAE"
white = "#e1e2e7"
