# Colors for h4ck3r Rice

# Default colors
[colors.primary]
background = "#0c1018"
foreground = "#1947e0"

# Cursor colors
[colors.cursor]
cursor = "#1947e0"
text = "#0c1018"

# Normal colors
[colors.normal]
black = "#4A9801"
red = "#6DDE00"
green = "#00fa5c"
yellow = "#76EA00"
blue = "#578a29"
magenta = "#9cf542"
cyan = "#539e06"
white = "#00ff59"

# Bright colors
[colors.bright]
black = "#03198a"
red = "#0800ff"
green = "#4145b0"
yellow = "#025dd4"
blue = "#7eb3f7"
magenta = "#220991"
cyan = "#3a11f0"
white = "#3b5eed"
