# Colors for Isabel Rice

# Default colors
[colors.primary]
background = "#14171c"
foreground = "#abb2bf"

# Cursor colors
[colors.cursor]
cursor = "#abb2bf"
text = "#14171c"

# Normal colors
[colors.normal]
black = "#181b21"
red = "#be5046"
green = "#81ae5f"
yellow = "#d19a66"
blue = "#4889be"
magenta = "#7560d3"
cyan = "#49919a"
white = "#abb2bf"

# Bright colors
[colors.bright]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#8677cf"
cyan = "#56b6c2"
white = "#b8bfe5"
