# Colors for Silvia Rice

# Default colors
[colors.primary]
background = "#282828"
foreground = "#fbf1c7"

# Cursor colors
[colors.cursor]
cursor = "#fbf1c7"
text = "#282828"

# Normal colors
[colors.normal]
black = "#a89984"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#ebdbb2"

# Bright colors
[colors.bright]
black = "#a89984"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"
