# Colors for Varinka Rice

# Default colors
[colors.primary]
background = "#212529"
foreground = "#f8f9fa"

# Cursor colors
[colors.cursor]
cursor = "#f8f9fa"
text = "#212529"

# Normal colors
[colors.normal]
black = "#2C3136"
red = "#dee2e6"
green = "#adb5bd"
yellow = "#e9ecef"
blue = "#495057"
magenta = "#ced4da"
cyan = "#6c757d"
white = "#f8f9fa"

# Bright colors
[colors.bright]
black = "#343a40"
red = "#dee2e6"
green = "#adb5bd"
yellow = "#e9ecef"
blue = "#495057"
magenta = "#ced4da"
cyan = "#6c757d"
white = "#f8f9fa"
