# Colors for Yael Rice

# Default colors
[colors.primary]
background = "#161616"
foreground = "#ffffff"

# Cursor colors
[colors.cursor]
cursor = "#ffffff"
text = "#161616"

# Normal colors
[colors.normal]
black = "#262626"
red = "#ee5396"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
magenta = "#ff7eb6"
cyan = "#3ddbd9"
white = "#dde1e6"

# Bright colors
[colors.bright]
black = "#393939"
red = "#ee5396"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
magenta = "#ff7eb6"
cyan = "#3ddbd9"
white = "#ffffff"
