#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
--menu)
  rofi -show drun -theme "$HOME"/.config/bspwm/src/rofi-themes/Launcher.rasi
  ;;
--rice)
  RiceSelector
  ;;
--terminal)
  Term --terminal
  ;;
--floating)
  Term --floating
  ;;
--update)
  Term --update
  ;;
--checkupdates)
  Term --checkupdates
  ;;
--netmanager)
  NetManagerDM
  ;;
--bluetooth)
  rofi-bluetooth
  ;;
--clipboard)
  rofi -modi "clipboard:greenclip print" -theme "$HOME"/.config/bspwm/src/rofi-themes/Clipboard.rasi -show clipboard -run-command '{cmd}'
  ;;
--screenshot)
  ScreenShoTer
  ;;
--powermenu)
  PowerMenu
  ;;
--ranger)
  Term --ranger
  ;;
--nvim)
  Term --nvim
  ;;
--music)
  Term --music
  ;;
--fetch)
  Term --fetch
  ;;

# Apps
--filemanager)
  thunar
  ;;
--browser)
  firefox
  ;;
--element)
  element
  ;;
--telegram)
  telegram-desktop
  ;;
--soundcontrol)
  pavucontrol
  ;;

# Eww Widgets
--KeyHelp)
  eww -c "$WIDGET_DIR" open --toggle csheet
  ;;
--usercard)
  eww -c "$WIDGET_DIR" open --toggle launchermenu
  ;;
--player)
  eww -c "$WIDGET_DIR" open --toggle music
  ;;
--calendar)
  eww -c "$WIDGET_DIR" open --toggle date
  ;;
*)
  echo "Invalid Option"
  ;;
esac
