#!/usr/bin/env bash

CONFIG_FILE="$HOME/.config/bspwm/src/config/system.ini"
SFILE="$HOME/.config/bspwm/src/.sys"

[[ -f "$SFILE" ]] && exit 0

setup_system_vars() {
  # Primary Network Interface Detection
  local primary_net=$(ip link | awk '/state UP/ {print $2}' | tr -d :)

  # Graphics card detection
  local card=$(ls /sys/class/backlight/ 2>/dev/null | head -n1)

  # Battery and adapter detection
  local battery=$(ls /sys/class/power_supply/ 2>/dev/null | grep -m1 'BAT')
  local adapter=$(ls /sys/class/power_supply/ 2>/dev/null | grep -m1 -E 'AC|ADP')

  # Atomic update of the configuration file
  tmpfile=$(mktemp)
  awk -v net="$primary_net" \
    -v card="$card" \
    -v bat="$battery" \
    -v adap="$adapter" '
        /^sys_network_interface =/ {$0="sys_network_interface = " net}
        /^sys_graphics_card =/ {$0="sys_graphics_card = " card}
        /^sys_battery =/ {$0="sys_battery = " bat}
        /^sys_adapter =/ {$0="sys_adapter = " adap}
        {print}
    ' "$CONFIG_FILE" >"$tmpfile" && mv "$tmpfile" "$CONFIG_FILE"
}

sleep 3
setup_system_vars
touch "$SFILE"
