#!/usr/bin/env bash

CFG_TERM="$HOME/.config/bspwm/src/.term"
DEFAULT_TERM="alacritty"
ROFI_THEME="$HOME/.config/bspwm/src/rofi-themes/TermSelector.rasi"

[ ! -f "$CFG_TERM" ] && echo "$DEFAULT_TERM" >"$CFG_TERM"

MY_TERM=$(<"$CFG_TERM")

choose_terminal() {
  local options=("Alacritty" "Kitty")
  local current_term=$(tr '[:upper:]' '[:lower:]' <"$CFG_TERM")

  local selected_index=$(printf '%s\n' "${options[@],,}" | awk -v cur="$current_term" '$0==cur {print NR-1; exit}')

  local chosen
  chosen=$(printf '%s\n' "${options[@]}" | rofi -theme "$ROFI_THEME" -mesg "[ Your current terminal is $MY_TERM ]" -dmenu -selected-row "$selected_index")

  [[ -n "$chosen" ]] && echo "${chosen,,}" >"$CFG_TERM"
}

[ "$1" = "--selecterm" ] && choose_terminal

case $MY_TERM in
"alacritty")
  case $1 in
  "--terminal")
    alacritty
    ;;
  "--floating")
    alacritty --class FloaTerm,FloaTerm
    ;;
  "--update")
    alacritty --hold --class FloaTerm,FloaTerm -e Updates --update-system
    ;;
  "--checkupdates")
    alacritty --hold --class Updating,Updating -e Updates --print-updates
    ;;
  "--yazi")
    alacritty --class FloaTerm,YaziTerm -e yazi
    ;;
  "--nvim")
    alacritty -e nvim
    ;;
  "--music")
    alacritty --class FloaTerm,MusicTerm -e ncmpcpp
    ;;
  "--fetch")
    alacritty --class FloaTerm,FetchTerm -e ~/.local/bin/sysfetch
    ;;
  "--scratch")
    tdrop -ma -w 70% -h 35% -y 0 -x 15% -n 0 --class scratch alacritty --class=Scratch
    ;;
  "--yaziscratch")
    tdrop -ma -w 80% -h 35% -y 0 -x 10% -n 1 --class scratch alacritty --class=Scratch -e yazi
    ;;
  esac
  ;;
"kitty")
  case $1 in
  "--terminal")
    kitty
    ;;
  "--floating")
    kitty --class=FloaTerm
    ;;
  "--update")
    kitty --hold --class=FloaTerm -e Updates --update-system
    ;;
  "--checkupdates")
    kitty --hold --class=Updating -e Updates --print-updates
    ;;
  "--yazi")
    kitty --hold --name=YaziTerm --class=FloaTerm -e yazi
    ;;
  "--nvim")
    kitty -e nvim
    ;;
  "--music")
    kitty --name=MusicTerm --class=FloaTerm -e ncmpcpp
    ;;
  "--fetch")
    kitty --name=FetchTerm --class=FloaTerm -e ~/.local/bin/sysfetch
    ;;
  "--scratch")
    tdrop -ma -w 70% -h 35% -y 0 -x 15% -n 0 --class scratch kitty --class=Scratch
    ;;
  "--yaziscratch")
    tdrop -ma -w 80% -h 35% -y 0 -x 10% -n 1 --class scratch kitty --class=Scratch -e yazi
    ;;
  esac
  ;;
esac
