#!/bin/sh

export PATH="$HOME/.config/bspwm/bin:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
# Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

## WORKSPACE

MonitorSetup

## BSPWM CONFIG

bspc config external_rules_command "${HOME}"/.config/bspwm/bin/ExternalRules

bspc config window_gap 5
bspc config split_ratio 0.51
bspc config single_monocle true

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

## AUTOSTART

run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}

# Set system vars for polybar
"$HOME"/.config/bspwm/bin/SetSysVars

# Launch sxhkd daemon
run sxhkd -c "${HOME}"/.config/bspwm/config/sxhkdrc

# Load current theme
"${HOME}"/.config/bspwm/bin/Theme.sh

# Launch picom
run picom --config "${HOME}"/.config/bspwm/config/picom.conf

# Launch xsettingsd
run xsettingsd --config="${HOME}"/.config/bspwm/config/xsettingsd >/dev/null 2>&1

# Launch eww daemon
pidof -q eww || { eww -c "${HOME}"/.config/bspwm/eww daemon & }

# Launch clipboard daemon
run clipcatd

# Launch clipboard daemon
pidof -q clipcatd || { clipcatd & }

# Launch polkit
run lxpolkit

# Start one time message
[ ! -f "$HOME/.config/bspwm/config/.first_run_done" ] && alacritty --hold -e sh -c 'cat "$HOME/.config/bspwm/config/FirstMessage.txt"; sleep 0.1' && touch "$HOME/.config/bspwm/config/.first_run_done"
