#!/usr/bin/env bash

is_online() {
	ping -c 1 -W 1 archlinux.org &>/dev/null
}

ID=$(ip link | awk '/state UP/ {print $2}' | tr -d :)

ICON="images/no-wifi.png"
STATUS="Offline"

if is_online; then
	ICON="images/wifi.png"

    if [[ $ID == e* ]]; then
        STATUS="$ID"
    elif command -v nmcli &>/dev/null; then
        STATUS=$(nmcli -t -f active,ssid dev wifi show | sed -n '1{s/SSID: //p}')
    fi
fi

case "$1" in
    --stat) echo "$STATUS" ;;
    --icon) echo "$ICON" ;;
esac
