#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
  --menu)
    rofi -show drun -theme "$HOME"/.config/bspwm/scripts/Launcher.rasi
    ;;
  --rice)
    RiceSelector
    ;;
  --terminal)
    Term --terminal
    ;;
  --floating)
    Term --floating
    ;;
  --update)
    Term --update
    ;;
  --checkupdates)
    Term --checkupdates
    ;;
  --netmanager)
    NetManagerDM
    ;;
  --ranger)
    Term --ranger
    ;;
  --nvim)
    Term --nvim
    ;;
  --music)
    Term --music
    ;;
  --fetch)
    Term --fetch
    ;;

  # Apps
  --filemanager)
    thunar
    ;;
  --browser)
    firefox
    ;;
  --element)
    element
    ;;
  --telegram)
    telegram-desktop
    ;;
  --soundcontrol)
    pavucontrol
    ;;

  # Eww Widgets
  --KeyHelp)
    eww -c "$WIDGET_DIR" open --toggle csheet
    ;;
  --powermenu)
    eww -c "$WIDGET_DIR" open --toggle powermenu
    ;;
  --usercard)
    eww -c "$WIDGET_DIR" open --toggle launchermenu
    ;;
  --player)
    eww -c "$WIDGET_DIR" open --toggle music
    ;;
  --calendar)
    eww -c "$WIDGET_DIR" open --toggle date
    ;;
  *)
    echo "Invalid Option"
    ;;
esac
